version: "2"
services:
  opa:
    hostname: opa
    image: openpolicyagent/opa:0.7.0
    ports:
      - 8181:8181
    command: "run --server --log-level=debug /data/kafka_authz.rego"
    volumes:
      - ./src/test/resources/:/data
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.2-1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      zk_id: "1"
  kafka:
    hostname: kafka
    image: confluentinc/cp-kafka:3.2.2-1
    links:
      - zookeeper
      - opa
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_AUTHORIZER_CLASS_NAME: com.lbg.kafka.opa.OpaAuthorizer
      KAFKA_OPA_AUTHORIZER_URL: "http://opa:8181/v1/data/kafka/authz/allow"
      KAFKA_OPA_AUTHORIZER_ALLOW_ON_ERROR: "false"
      KAFKA_OPA_CACHE_INITIAL_CAPACITY: 100
      KAFKA_OPA_CACHE_MAXIMUM_SIZE: 100
      KAFKA_OPA_CACHE_EXPIRE_AFTER_MS: 600000
      CLASSPATH: /jars/kafka-authorizer-opa-1.0-SNAPSHOT.jar:/jars/gson-2.8.2.jar
    volumes:
      - ./target/kafka-authorizer-opa-1.0-SNAPSHOT-package/share/java/kafka-authorizer-opa/:/jars
